version: '2.1'
services:
  etcd:
    image: smithx10/etcd:latest
    mem_limit: 128m
    ports:
      - 4001
      - 2379
      - 2380
    links:
      - consul:consul
    restart: always
    network_mode: bridge
    environment:
      - CONSUL=consul
      - CONSUL_AGENT=1
    command: >-
      /usr/local/bin/containerpilot

  etcd-bootstrap:
    image: smithx10/etcd:latest
    mem_limit: 128m
    ports:
      - 4001
      - 2379
      - 2380
    environment:
      - CONSUL=consul
      - CONSUL_AGENT=1
      - ETCD_BOOTSTRAP=1
    network_mode: bridge
    hostname: bootstrap
    links:
      - consul:consul
    command: >-
      /usr/local/bin/containerpilot

  consul:
    image: autopilotpattern/consul:${TAG:-latest}
    command: >
       /usr/local/bin/containerpilot
    restart: always
    mem_limit: 128m
    ports:
      - 8500:8500
    network_mode: bridge
    environment:
      - CONSUL=consul
      - CONSUL_DEV=1
